# -*- coding: utf-8 -*-
"""final_project2_code1 (2).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iIvCzjOeuKGv6WL3tScEOihub77eHIyM
"""

pip install ultralytics

import zipfile
import os

zip_path = "/content/archive (8).zip"
extract_path = "/content/dataset"

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_path)

print("Dataset extracted successfully!")

from ultralytics import YOLO

# Commented out IPython magic to ensure Python compatibility.
# %%writefile /content/dataset/data_road_224.yaml
# path: /content/dataset/data_road_224
# train: /content/dataset/data_road_224/training/image_2
# test: /content/dataset/data_road_224/testing/image_2
# 
# nc: 2  # Change based on the number of classes
# names: ['car', 'truck']  # Modify class names accordingly

# Commented out IPython magic to ensure Python compatibility.
# %%writefile /content/dataset/KITTI/dataset.yaml
# path: /content/dataset/KITTI
# train: training_/image_2
# val: testing_/image_2  # Using test set as validation
# 
# nc: 2  # Number of classes: car and bus
# names: ['car', 'bus']  # Modify class names accordingly

# Commented out IPython magic to ensure Python compatibility.
# %%writefile /content/dataset/data_road_224.yaml
# path: /content/dataset/data_road_224
# train: /content/dataset/data_road_224/training/image_2
# val: /content/dataset/data_road_224/testing/image_2  # Added val: key, using test set as validation
# 
# nc: 2  # Change based on the number of classes
# names: ['car', 'truck']  # Modify class names accordingly

from ultralytics import YOLO

model = YOLO("yolov8n.yaml")

model.train(
    data="/content/dataset/data_road_224.yaml",
    epochs=50,
    imgsz=640,
    batch=16
)

import pandas as pd

results_df = pd.read_csv("runs/detect/train4/results.csv")
print(results_df.tail())

import os
import cv2
import numpy as np
import torch
import torchvision.ops as ops
from PIL import Image
from torchvision import transforms, models
from ultralytics import YOLO
from transformers import DetrImageProcessor, DetrForObjectDetection

# Load Models
def load_yolov8():
    return YOLO("yolov8n.pt")

def load_detr():
    detr_processor = DetrImageProcessor.from_pretrained("facebook/detr-resnet-50")
    detr_model = DetrForObjectDetection.from_pretrained("facebook/detr-resnet-50")
    detr_model.eval()
    return detr_processor, detr_model

def load_faster_rcnn():
    rcnn_model = models.detection.fasterrcnn_resnet50_fpn(pretrained=True)
    rcnn_model.eval()
    return rcnn_model

# Load all models
yolo_model = load_yolov8()
detr_processor, detr_model = load_detr()
faster_rcnn_model = load_faster_rcnn()

# COCO Labels
COCO_INSTANCE_CATEGORY_NAMES = [
    '__background__', 'person', 'bicycle', 'car', 'motorcycle', 'airplane', 'bus', 'train',
    'truck', 'boat', 'traffic light', 'fire hydrant', 'stop sign', 'parking meter', 'bench'
]
ALLOWED_CLASSES = {"car", "truck", "bus", "motorcycle"}

# Confidence Thresholds
RCNN_CONF_THRESHOLD = 0.75
YOLO_CONF_THRESHOLD = 0.7
DETR_CONF_THRESHOLD = 0.6

# Accuracy Computation
def compute_accuracy(confidences):
    return np.mean(confidences) if confidences else 0.0

# Detection Functions
def detect_with_yolo(frame):
    results = yolo_model(frame)
    detected_boxes, confidences = [], []
    for result in results:
        for box, conf in zip(result.boxes.xyxy, result.boxes.conf):
            if conf > YOLO_CONF_THRESHOLD:
                detected_boxes.append(box.cpu().numpy().astype(int))
                confidences.append(conf.item())
    return detected_boxes, confidences

def detect_with_detr(image):
    inputs = detr_processor(images=image, return_tensors="pt")
    with torch.no_grad():
        outputs = detr_model(**inputs)
    target_sizes = torch.tensor([image.size[::-1]])
    results = detr_processor.post_process_object_detection(outputs, target_sizes=target_sizes, threshold=DETR_CONF_THRESHOLD)[0]

    boxes = [list(map(int, box.tolist())) for box in results["boxes"]]
    scores = results["scores"].tolist()
    return boxes, scores

def detect_with_faster_rcnn(frame):
    transform = transforms.ToTensor()
    image = transform(frame).unsqueeze(0)
    with torch.no_grad():
        predictions = faster_rcnn_model(image)

    detected_boxes, confidences = [], []
    if "boxes" not in predictions[0] or len(predictions[0]["boxes"]) == 0:
        return detected_boxes, confidences  # No detections, return empty lists

    for box, score, label in zip(predictions[0]['boxes'], predictions[0]['scores'], predictions[0]['labels']):
        label_idx = label.item()
        if 0 <= label_idx < len(COCO_INSTANCE_CATEGORY_NAMES):  # Check index validity
            class_name = COCO_INSTANCE_CATEGORY_NAMES[label_idx]
            if score > RCNN_CONF_THRESHOLD and class_name in ALLOWED_CLASSES:
                detected_boxes.append(box.cpu().numpy().astype(int))
                confidences.append(score.item())

    return detected_boxes, confidences

# Non-Maximum Suppression (NMS)
def apply_nms(boxes, scores, iou_threshold=0.5):
    if len(boxes) == 0:
        return [], []
    boxes_tensor = torch.tensor(boxes, dtype=torch.float32)
    scores_tensor = torch.tensor(scores, dtype=torch.float32)
    keep = ops.nms(boxes_tensor, scores_tensor, iou_threshold)
    return [boxes[i] for i in keep], [scores[i] for i in keep]

# Heatmap Generation
def generate_heatmap(frame, detected_boxes):
    heatmap = np.zeros((frame.shape[0], frame.shape[1]), dtype=np.float32)
    for box in detected_boxes:
        xmin, ymin, xmax, ymax = box
        heatmap[ymin:ymax, xmin:xmax] += 1

    heatmap = cv2.GaussianBlur(heatmap, (25, 25), 0)
    heatmap = (heatmap / np.max(heatmap) * 255).astype(np.uint8) if np.max(heatmap) > 0 else heatmap
    heatmap = cv2.applyColorMap(heatmap, cv2.COLORMAP_JET)
    return cv2.addWeighted(frame, 0.6, heatmap, 0.4, 0)

# Detection Pipeline
def detect_traffic_insights(video_path, output_dir, display=False, detr_every_n_frames=2):
    os.makedirs(output_dir, exist_ok=True)
    cap = cv2.VideoCapture(video_path)
    frame_count = 0

    detr_confidences, rcnn_confidences, yolo_confidences = [], [], []
    vehicle_counts = []

    while cap.isOpened():
        ret, frame = cap.read()
        if not ret:
            break

        image_pil = Image.fromarray(cv2.cvtColor(frame, cv2.COLOR_BGR2RGB))
        detected_boxes, scores = [], []

        # Use DETR every 2 frames
        if frame_count % detr_every_n_frames == 0:
            detr_boxes, detr_scores = detect_with_detr(image_pil)
            detected_boxes.extend(detr_boxes)
            scores.extend(detr_scores)
            detr_confidences.extend(detr_scores)

        # YOLO + Faster R-CNN every other frame
        else:
            yolo_boxes, yolo_scores = detect_with_yolo(frame)
            rcnn_boxes, rcnn_scores = detect_with_faster_rcnn(frame)

            detected_boxes.extend(yolo_boxes + rcnn_boxes)
            scores.extend(yolo_scores + rcnn_scores)

            yolo_confidences.extend(yolo_scores)
            rcnn_confidences.extend(rcnn_scores)

        # Apply NMS
        detected_boxes, scores = apply_nms(detected_boxes, scores)

        # Draw bounding boxes with unique labels
        vehicle_id = 1
        for (xmin, ymin, xmax, ymax) in detected_boxes:
            frame = cv2.rectangle(frame, (xmin, ymin), (xmax, ymax), (0, 255, 0), 2)
            label = f"{vehicle_id}"
            cv2.putText(frame, label, (xmin, ymin - 10), cv2.FONT_HERSHEY_SIMPLEX, 0.9, (0, 255, 0), 2)
            vehicle_id += 1

        # Generate heatmap
        frame = generate_heatmap(frame, detected_boxes)

        # Count vehicles safely
        vehicle_count = sum(1 for box in detected_boxes if len(box) == 4)
        vehicle_counts.append(vehicle_count)

        # Save frame
        output_frame_path = os.path.join(output_dir, f"frame_{frame_count:04d}.jpg")
        cv2.imwrite(output_frame_path, frame)
        frame_count += 1

        if display:
            cv2.imshow("Frame", frame)
            if cv2.waitKey(1) & 0xFF == ord('q'):
                break

    cap.release()

    # Compute final accuracies
    overall_acc = compute_accuracy(detr_confidences + rcnn_confidences + yolo_confidences)
    avg_vehicle_count = np.mean(vehicle_counts) if vehicle_counts else 0

    print(f"Overall Accuracy: {overall_acc:.2f}")
    print(f"Average Vehicle Count: {avg_vehicle_count:.2f}")
    print(f"Processed {frame_count} frames. Results saved in {output_dir}")

# Run Detection
video_path = "/content/traff.mp4"
output_directory = "processed_frames_optimized"
detect_traffic_insights(video_path, output_directory, display=False)

import os
import cv2
import numpy as np
import torch
import torchvision.ops as ops
from PIL import Image
from torchvision import transforms, models
from ultralytics import YOLO
from transformers import DetrImageProcessor, DetrForObjectDetection

# Load Models
def load_yolov8():
    return YOLO("yolov8n.pt")

def load_detr():
    detr_processor = DetrImageProcessor.from_pretrained("facebook/detr-resnet-50")
    detr_model = DetrForObjectDetection.from_pretrained("facebook/detr-resnet-50")
    detr_model.eval()
    return detr_processor, detr_model

def load_faster_rcnn():
    rcnn_model = models.detection.fasterrcnn_resnet50_fpn(pretrained=True)
    rcnn_model.eval()
    return rcnn_model

yolo_model = load_yolov8()
detr_processor, detr_model = load_detr()
faster_rcnn_model = load_faster_rcnn()

# COCO Labels
COCO_INSTANCE_CATEGORY_NAMES = [
    '__background__', 'person', 'bicycle', 'car', 'motorcycle', 'airplane', 'bus', 'train',
    'truck', 'boat', 'traffic light', 'fire hydrant', 'stop sign', 'parking meter', 'bench'
]
ALLOWED_CLASSES = {"car", "truck", "bus", "motorcycle"}

# Confidence Thresholds
RCNN_CONF_THRESHOLD = 0.75
YOLO_CONF_THRESHOLD = 0.7
DETR_CONF_THRESHOLD = 0.6

# Accuracy Computation
def compute_accuracy(confidences):
    return np.mean(confidences) if confidences else 0.0

# Detection Functions
def detect_with_yolo(frame):
    results = yolo_model(frame)
    detected_boxes, confidences = [], []
    for result in results:
        for box, conf in zip(result.boxes.xyxy, result.boxes.conf):
            if conf > YOLO_CONF_THRESHOLD:
                detected_boxes.append(box.cpu().numpy().astype(int))
                confidences.append(conf.item())
    return detected_boxes, confidences

def detect_with_detr(image):
    inputs = detr_processor(images=image, return_tensors="pt")
    with torch.no_grad():
        outputs = detr_model(**inputs)
    target_sizes = torch.tensor([image.size[::-1]])
    results = detr_processor.post_process_object_detection(outputs, target_sizes=target_sizes, threshold=DETR_CONF_THRESHOLD)[0]

    boxes = [list(map(int, box.tolist())) for box in results["boxes"]]
    scores = results["scores"].tolist()
    return boxes, scores

def detect_with_faster_rcnn(frame):
    transform = transforms.ToTensor()
    image = transform(frame).unsqueeze(0)
    with torch.no_grad():
        predictions = faster_rcnn_model(image)

    detected_boxes, confidences = [], []
    if "boxes" not in predictions[0] or len(predictions[0]["boxes"]) == 0:
        return detected_boxes, confidences  # No detections, return empty lists

    for box, score, label in zip(predictions[0]['boxes'], predictions[0]['scores'], predictions[0]['labels']):
        label_idx = label.item()
        if 0 <= label_idx < len(COCO_INSTANCE_CATEGORY_NAMES):  # Check index validity
            class_name = COCO_INSTANCE_CATEGORY_NAMES[label_idx]
            if score > RCNN_CONF_THRESHOLD and class_name in ALLOWED_CLASSES:
                detected_boxes.append(box.cpu().numpy().astype(int))
                confidences.append(score.item())

    return detected_boxes, confidences

# Non-Maximum Suppression (NMS)
def apply_nms(boxes, scores, iou_threshold=0.5):
    if len(boxes) == 0:
        return [], []
    boxes_tensor = torch.tensor(boxes, dtype=torch.float32)
    scores_tensor = torch.tensor(scores, dtype=torch.float32)
    keep = ops.nms(boxes_tensor, scores_tensor, iou_threshold)
    return [boxes[i] for i in keep], [scores[i] for i in keep]

# Heatmap
def generate_heatmap(frame, detected_boxes):
    heatmap = np.zeros((frame.shape[0], frame.shape[1]), dtype=np.float32)
    for box in detected_boxes:
        xmin, ymin, xmax, ymax = box
        heatmap[ymin:ymax, xmin:xmax] += 1

    heatmap = cv2.GaussianBlur(heatmap, (25, 25), 0)
    heatmap = (heatmap / np.max(heatmap) * 255).astype(np.uint8) if np.max(heatmap) > 0 else heatmap
    heatmap = cv2.applyColorMap(heatmap, cv2.COLORMAP_JET)
    return cv2.addWeighted(frame, 0.6, heatmap, 0.4, 0)

# Detection Pipeline with Video Output
def detect_traffic_insights(video_path, output_video_path, detr_every_n_frames=2):
    cap = cv2.VideoCapture(video_path)
    frame_count = 0

    # Get video properties
    width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
    height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
    fps = int(cap.get(cv2.CAP_PROP_FPS))

    # Define VideoWriter
    fourcc = cv2.VideoWriter_fourcc(*'mp4v')  # Codec for MP4 format
    out = cv2.VideoWriter(output_video_path, fourcc, fps, (width, height))

    detr_confidences, rcnn_confidences, yolo_confidences = [], [], []

    while cap.isOpened():
        ret, frame = cap.read()
        if not ret:
            break

        image_pil = Image.fromarray(cv2.cvtColor(frame, cv2.COLOR_BGR2RGB))
        detected_boxes, scores = [], []

        # Use DETR every 2 frames
        if frame_count % detr_every_n_frames == 0:
            detr_boxes, detr_scores = detect_with_detr(image_pil)
            detected_boxes.extend(detr_boxes)
            scores.extend(detr_scores)
            detr_confidences.extend(detr_scores)

        # YOLO + Faster R-CNN every other frame
        else:
            yolo_boxes, yolo_scores = detect_with_yolo(frame)
            rcnn_boxes, rcnn_scores = detect_with_faster_rcnn(frame)

            detected_boxes.extend(yolo_boxes + rcnn_boxes)
            scores.extend(yolo_scores + rcnn_scores)

            yolo_confidences.extend(yolo_scores)
            rcnn_confidences.extend(rcnn_scores)

        # Apply NMS
        detected_boxes, scores = apply_nms(detected_boxes, scores)

        # Draw bounding boxes
        for (xmin, ymin, xmax, ymax) in detected_boxes:
            frame = cv2.rectangle(frame, (xmin, ymin), (xmax, ymax), (0, 255, 0), 2)

        # Generate heatmap
        frame = generate_heatmap(frame, detected_boxes)

        # Write frame to video
        out.write(frame)

        frame_count += 1
        print(f"Processed Frame {frame_count}")

    cap.release()
    out.release()

    # Compute final accuracies
    detr_acc = compute_accuracy(detr_confidences)
    rcnn_acc = compute_accuracy(rcnn_confidences)
    yolo_acc = compute_accuracy(yolo_confidences)
    overall_acc = compute_accuracy(detr_confidences + rcnn_confidences + yolo_confidences)

    print(f"Final DETR Accuracy: {detr_acc:.2f}")
    print(f"Final Faster R-CNN Accuracy: {rcnn_acc:.2f}")
    print(f"Final YOLOv8 Accuracy: {yolo_acc:.2f}")
    print(f"Overall Accuracy: {overall_acc:.2f}")
    print(f"Processed {frame_count} frames. Output saved to {output_video_path}")

# Run Detection
video_path = "/content/traff.mp4"
output_video_path = "processed_video.mp4"
detect_traffic_insights(video_path, output_video_path)

!pip install deep-sort-realtime

import locale
def getpreferredencoding(do_setlocale = True):
    return "UTF-8"
locale.getpreferredencoding = getpreferredencoding
!pip install deep-sort-realtime

from ultralytics import YOLO
from deep_sort_realtime.deepsort_tracker import DeepSort
import cv2
import numpy as np
import time
import os
import torch
import torchvision.ops as ops
from PIL import Image
from torchvision import transforms, models
from transformers import DetrImageProcessor, DetrForObjectDetection

# ---------------------------
# Model Loading and Initialization
# ---------------------------

# Define input and output paths
video_path = "/content/traff.mp4"
output_path = "processed_video.mp4"  # Single unified output file

# Load YOLOv8 model (for both tracking and detection)
print("[INFO] Loading YOLOv8 model...")
yolo_model = YOLO("yolov8n.pt")

# Load Deep SORT (tracking)
deep_sort = DeepSort(max_age=15, n_init=5)

# Load DETR (detection)
def load_detr():
    detr_processor = DetrImageProcessor.from_pretrained("facebook/detr-resnet-50")
    detr_model = DetrForObjectDetection.from_pretrained("facebook/detr-resnet-50")
    detr_model.eval()
    return detr_processor, detr_model

detr_processor, detr_model = load_detr()

# Load Faster R-CNN (detection)
def load_faster_rcnn():
    rcnn_model = models.detection.fasterrcnn_resnet50_fpn(pretrained=True)
    rcnn_model.eval()
    return rcnn_model

faster_rcnn_model = load_faster_rcnn()

# COCO labels and allowed classes (for Faster R-CNN)
COCO_INSTANCE_CATEGORY_NAMES = [
    '__background__', 'person', 'bicycle', 'car', 'motorcycle', 'airplane', 'bus', 'train',
    'truck', 'boat', 'traffic light', 'fire hydrant', 'stop sign', 'parking meter', 'bench'
]
ALLOWED_CLASSES = {"car", "truck", "bus", "motorcycle"}

# Confidence thresholds for detection models
RCNN_CONF_THRESHOLD = 0.75
YOLO_CONF_THRESHOLD = 0.7
DETR_CONF_THRESHOLD = 0.6

# ---------------------------
# Utility Functions (Detection Pipeline)
# ---------------------------

def compute_accuracy(confidences):
    return np.mean(confidences) if confidences else 0.0

def detect_with_yolo(frame):
    results = yolo_model(frame)
    detected_boxes, confidences = [], []
    for result in results:
        for box, conf in zip(result.boxes.xyxy, result.boxes.conf):
            if conf > YOLO_CONF_THRESHOLD:
                detected_boxes.append(box.cpu().numpy().astype(int))
                confidences.append(conf.item())
    return detected_boxes, confidences

def detect_with_detr(image):
    inputs = detr_processor(images=image, return_tensors="pt")
    with torch.no_grad():
        outputs = detr_model(**inputs)
    target_sizes = torch.tensor([image.size[::-1]])
    results = detr_processor.post_process_object_detection(
        outputs,
        target_sizes=target_sizes,
        threshold=DETR_CONF_THRESHOLD
    )[0]
    boxes = [list(map(int, box.tolist())) for box in results["boxes"]]
    scores = results["scores"].tolist()
    return boxes, scores

def detect_with_faster_rcnn(frame):
    transform = transforms.ToTensor()
    image = transform(frame).unsqueeze(0)
    with torch.no_grad():
        predictions = faster_rcnn_model(image)
    detected_boxes, confidences = [], []
    if "boxes" not in predictions[0] or len(predictions[0]["boxes"]) == 0:
        return detected_boxes, confidences  # No detections
    for box, score, label in zip(predictions[0]['boxes'], predictions[0]['scores'], predictions[0]['labels']):
        label_idx = label.item()
        if 0 <= label_idx < len(COCO_INSTANCE_CATEGORY_NAMES):
            class_name = COCO_INSTANCE_CATEGORY_NAMES[label_idx]
            if score > RCNN_CONF_THRESHOLD and class_name in ALLOWED_CLASSES:
                detected_boxes.append(box.cpu().numpy().astype(int))
                confidences.append(score.item())
    return detected_boxes, confidences

def apply_nms(boxes, scores, iou_threshold=0.5):
    if len(boxes) == 0:
        return [], []
    boxes_tensor = torch.tensor(boxes, dtype=torch.float32)
    scores_tensor = torch.tensor(scores, dtype=torch.float32)
    keep = ops.nms(boxes_tensor, scores_tensor, iou_threshold)
    return [boxes[i] for i in keep], [scores[i] for i in keep]

def generate_heatmap(frame, detected_boxes):
    heatmap = np.zeros((frame.shape[0], frame.shape[1]), dtype=np.float32)
    for box in detected_boxes:
        xmin, ymin, xmax, ymax = box
        heatmap[ymin:ymax, xmin:xmax] += 1
    if np.max(heatmap) > 0:
        heatmap = cv2.GaussianBlur(heatmap, (25, 25), 0)
        heatmap = (heatmap / np.max(heatmap) * 255).astype(np.uint8)
        heatmap = cv2.applyColorMap(heatmap, cv2.COLORMAP_JET)
    return cv2.addWeighted(frame, 0.6, heatmap, 0.4, 0)

# ---------------------------
# Utility Functions (Tracking Pipeline)
# ---------------------------

# Manually chosen points for homography (scene-dependent)
source_points = np.array([[320, 520], [980, 520], [100, 750], [1100, 750]], dtype=np.float32)
destination_points = np.array([[320, 520], [980, 520], [320, 900], [980, 900]], dtype=np.float32)
H_matrix, _ = cv2.findHomography(source_points, destination_points)

def calibrate_mpp(frame_height):
    reference_lane_width_px = frame_height / 10  # approximate lane width in pixels
    lane_width_meters = 3.7  # average lane width in meters
    return lane_width_meters / reference_lane_width_px

# ---------------------------
# Video Capture and Writer Setup
# ---------------------------

cap = cv2.VideoCapture(video_path)
fps = int(cap.get(cv2.CAP_PROP_FPS))
W = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
H = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
if fps == 0:
    fps = 30

writer = cv2.VideoWriter(output_path, cv2.VideoWriter_fourcc(*"mp4v"), fps, (W, H), True)

meters_per_pixel = calibrate_mpp(H)

# ---------------------------
# Tracking: Speed Estimation Function
# ---------------------------

def estimate_speed(prev, curr, fps, track_id):
    prev_transformed = cv2.perspectiveTransform(np.array([[prev]], dtype=np.float32), H_matrix)[0][0]
    curr_transformed = cv2.perspectiveTransform(np.array([[curr]], dtype=np.float32), H_matrix)[0][0]
    dist_px = np.linalg.norm(np.array(curr_transformed) - np.array(prev_transformed))
    if dist_px > 100:
        return speed_dict.get(track_id, [0])[-1]  # use previous value if jump is too large
    time_diff = 1 / fps
    if time_diff == 0:
        return 0
    speed_mps = (dist_px * meters_per_pixel) / time_diff  # in m/s
    speed_kmh = speed_mps * 3.6
    if track_id in speed_dict:
        speed_dict[track_id].append(speed_kmh)
        if len(speed_dict[track_id]) > 10:
            speed_dict[track_id].pop(0)
        avg_speed = np.mean(speed_dict[track_id])
        if abs(speed_kmh - avg_speed) > 50:
            return avg_speed
        return avg_speed
    else:
        speed_dict[track_id] = [speed_kmh]
        return speed_kmh

# ---------------------------
# Initialize Counters and Data Structures
# ---------------------------

frame_count = 0
total_frames = 0
detected_vehicles = 0
total_vehicles = 0

centroid_dict = {}
speed_dict = {}
prev_boxes = {}

# For detection pipeline accuracy bookkeeping
detr_confidences = []
rcnn_confidences = []
yolo_confidences = []
detr_every_n_frames = 2

# ---------------------------
# Main Processing Loop
# ---------------------------

while True:
    ret, frame = cap.read()
    if not ret:
        break

    # Work on a copy for annotations
    annotated_frame = frame.copy()

    # --- Tracking Pipeline: YOLO + Deep SORT ---
    results = yolo_model(frame)[0]
    detections = []
    frame_vehicles = 0
    for r in results.boxes.data:
        x1, y1, x2, y2, conf, cls = r.tolist()
        if conf >= 0.5 and int(cls) in [2, 3, 5, 7]:  # filter for vehicles
            detections.append(([x1, y1, x2, y2], conf, 'vehicle'))
            frame_vehicles += 1
    total_vehicles += frame_vehicles
    tracks = deep_sort.update_tracks(detections, frame=frame)
    for track in tracks:
        if not track.is_confirmed() or track.time_since_update > 1:
            continue
        x1, y1, x2, y2 = track.to_tlbr()
        track_id = track.track_id
        centroid = [(x1 + x2) // 2, (y1 + y2) // 2]
        detected_vehicles += 1
        prev_boxes[track_id] = [x1, y1, x2, y2]
        speed = estimate_speed(centroid_dict.get(track_id, centroid), centroid, fps, track_id)
        centroid_dict[track_id] = centroid
        # Draw tracking rectangle (green) and speed label
        cv2.rectangle(annotated_frame, (int(x1), int(y1)), (int(x2), int(y2)), (0, 255, 0), 2)
        cv2.putText(annotated_frame, f"ID {track_id} | {speed:.1f} km/h", (int(x1), int(y1) - 10),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 255, 0), 2)

    # --- Detection Pipeline: Multi-Model Detection and Heatmap ---
    detected_boxes = []
    scores = []

    # Use DETR every few frames; otherwise, use YOLO and Faster R-CNN
    if frame_count % detr_every_n_frames == 0:
        image_pil = Image.fromarray(cv2.cvtColor(frame, cv2.COLOR_BGR2RGB))
        detr_boxes, detr_scores = detect_with_detr(image_pil)
        detected_boxes.extend(detr_boxes)
        scores.extend(detr_scores)
        detr_confidences.extend(detr_scores)
    else:
        yolo_boxes, yolo_scores = detect_with_yolo(frame)
        rcnn_boxes, rcnn_scores = detect_with_faster_rcnn(frame)
        detected_boxes.extend(yolo_boxes + rcnn_boxes)
        scores.extend(yolo_scores + rcnn_scores)
        yolo_confidences.extend(yolo_scores)
        rcnn_confidences.extend(rcnn_scores)

    # Apply Non-Maximum Suppression
    detected_boxes, scores = apply_nms(detected_boxes, scores)

    # Draw detection boxes (using blue for distinction)
    for (xmin, ymin, xmax, ymax) in detected_boxes:
        cv2.rectangle(annotated_frame, (xmin, ymin), (xmax, ymax), (255, 0, 0), 2)

    # Overlay a heatmap using the detection boxes
    annotated_frame = generate_heatmap(annotated_frame, detected_boxes)

    writer.write(annotated_frame)
    frame_count += 1
    total_frames += 1
    print(f"Processed Frame {frame_count}")

cap.release()
writer.release()
cv2.destroyAllWindows()

# ---------------------------
# Post-Processing Metrics
# ---------------------------
avg_vehicles_per_frame = total_vehicles / total_frames if total_frames > 0 else 1
accuracy_tracking = (detected_vehicles / total_vehicles) * 100 if total_vehicles > 0 else 0

detr_acc = compute_accuracy(detr_confidences)
rcnn_acc = compute_accuracy(rcnn_confidences)
yolo_acc = compute_accuracy(yolo_confidences)
overall_acc = compute_accuracy(detr_confidences + rcnn_confidences + yolo_confidences)

print(f"Processed {total_frames} frames, Avg Vehicles/Frame: {avg_vehicles_per_frame:.2f}, Estimated Accuracy: {accuracy_tracking:.2f}%")
print(f"Final DETR Accuracy: {detr_acc:.2f}")
print(f"Final Faster R-CNN Accuracy: {rcnn_acc:.2f}")
print(f"Final YOLOv8 Accuracy: {yolo_acc:.2f}")
print(f"Overall Accuracy: {overall_acc:.2f}")
print(f" Output saved to: {output_path}")

import torch
from PIL import Image
from transformers import DetrImageProcessor, DetrForObjectDetection

# Load the pre-trained DETR model
detr_processor = DetrImageProcessor.from_pretrained("facebook/detr-resnet-50")
detr_model = DetrForObjectDetection.from_pretrained("facebook/detr-resnet-50")
detr_model.eval()

# Load an image (Replace with actual image)
image = Image.open("/content/ezgif-frame-001.jpg")
inputs = detr_processor(images=image, return_tensors="pt")

# Get DETR predictions
with torch.no_grad():
    outputs = detr_model(**inputs)

# Convert to bounding boxes
target_sizes = torch.tensor([image.size[::-1]])  # Convert to (H, W)
results = detr_processor.post_process_object_detection(
    outputs, target_sizes=target_sizes, threshold=0.5  # Threshold for confidence
)[0]

# Extract detected boxes & scores
predicted_boxes = results["boxes"].tolist()
predicted_scores = results["scores"].tolist()
predicted_labels = results["labels"].tolist()  # Class IDs

print(f"Detected Boxes: {predicted_boxes}")
print(f"Confidence Scores: {predicted_scores}")
print(f"Class Labels: {predicted_labels}")

from ultralytics import YOLO
from deep_sort_realtime.deepsort_tracker import DeepSort
import cv2
import numpy as np
import time
import os
import torch
import torchvision.ops as ops
from PIL import Image
from torchvision import transforms, models
from transformers import DetrImageProcessor, DetrForObjectDetection

# ---------------------------
# Model Loading and Initialization
# ---------------------------

# Define input and output paths
video_path = "/content/traf1.mp4"
output_path = "processed_video.mp4"  # Single unified output file

# Load YOLOv8 model (for both tracking and detection)
print("[INFO] Loading YOLOv8 model...")
yolo_model = YOLO("yolov8n.pt")

# Load Deep SORT (tracking)
deep_sort = DeepSort(max_age=15, n_init=5)

# Load DETR (detection)
def load_detr():
    detr_processor = DetrImageProcessor.from_pretrained("facebook/detr-resnet-50")
    detr_model = DetrForObjectDetection.from_pretrained("facebook/detr-resnet-50")
    detr_model.eval()
    return detr_processor, detr_model

detr_processor, detr_model = load_detr()

# Load Faster R-CNN (detection)
def load_faster_rcnn():
    rcnn_model = models.detection.fasterrcnn_resnet50_fpn(pretrained=True)
    rcnn_model.eval()
    return rcnn_model

faster_rcnn_model = load_faster_rcnn()

# COCO labels and allowed classes (for Faster R-CNN)
COCO_INSTANCE_CATEGORY_NAMES = [
    '__background__', 'person', 'bicycle', 'car', 'motorcycle', 'airplane', 'bus', 'train',
    'truck', 'boat', 'traffic light', 'fire hydrant', 'stop sign', 'parking meter', 'bench'
]
ALLOWED_CLASSES = {"car", "truck", "bus", "motorcycle"}

# Confidence thresholds for detection models
RCNN_CONF_THRESHOLD = 0.75
YOLO_CONF_THRESHOLD = 0.7
DETR_CONF_THRESHOLD = 0.6

# ---------------------------
# Utility Functions (Detection Pipeline)
# ---------------------------

def compute_accuracy(confidences):
    return np.mean(confidences) if confidences else 0.0

def detect_with_yolo(frame):
    results = yolo_model(frame)
    detected_boxes, confidences = [], []
    for result in results:
        for box, conf in zip(result.boxes.xyxy, result.boxes.conf):
            if conf > YOLO_CONF_THRESHOLD:
                detected_boxes.append(box.cpu().numpy().astype(int))
                confidences.append(conf.item())
    return detected_boxes, confidences

def detect_with_detr(image):
    inputs = detr_processor(images=image, return_tensors="pt")
    with torch.no_grad():
        outputs = detr_model(**inputs)
    target_sizes = torch.tensor([image.size[::-1]])
    results = detr_processor.post_process_object_detection(
        outputs,
        target_sizes=target_sizes,
        threshold=DETR_CONF_THRESHOLD
    )[0]
    boxes = [list(map(int, box.tolist())) for box in results["boxes"]]
    scores = results["scores"].tolist()
    return boxes, scores

def detect_with_faster_rcnn(frame):
    transform = transforms.ToTensor()
    image = transform(frame).unsqueeze(0)
    with torch.no_grad():
        predictions = faster_rcnn_model(image)
    detected_boxes, confidences = [], []
    if "boxes" not in predictions[0] or len(predictions[0]["boxes"]) == 0:
        return detected_boxes, confidences  # No detections
    for box, score, label in zip(predictions[0]['boxes'], predictions[0]['scores'], predictions[0]['labels']):
        label_idx = label.item()
        if 0 <= label_idx < len(COCO_INSTANCE_CATEGORY_NAMES):
            class_name = COCO_INSTANCE_CATEGORY_NAMES[label_idx]
            if score > RCNN_CONF_THRESHOLD and class_name in ALLOWED_CLASSES:
                detected_boxes.append(box.cpu().numpy().astype(int))
                confidences.append(score.item())
    return detected_boxes, confidences

def apply_nms(boxes, scores, iou_threshold=0.5):
    if len(boxes) == 0:
        return [], []
    boxes_tensor = torch.tensor(boxes, dtype=torch.float32)
    scores_tensor = torch.tensor(scores, dtype=torch.float32)
    keep = ops.nms(boxes_tensor, scores_tensor, iou_threshold)
    return [boxes[i] for i in keep], [scores[i] for i in keep]

def generate_heatmap(frame, detected_boxes):
    heatmap = np.zeros((frame.shape[0], frame.shape[1]), dtype=np.float32)
    for box in detected_boxes:
        xmin, ymin, xmax, ymax = box
        heatmap[ymin:ymax, xmin:xmax] += 1
    if np.max(heatmap) > 0:
        heatmap = cv2.GaussianBlur(heatmap, (25, 25), 0)
        heatmap = (heatmap / np.max(heatmap) * 255).astype(np.uint8)
        heatmap = cv2.applyColorMap(heatmap, cv2.COLORMAP_JET)
    return cv2.addWeighted(frame, 0.6, heatmap, 0.4, 0)

# ---------------------------
# Utility Functions (Tracking Pipeline)
# ---------------------------

# Manually chosen points for homography (scene-dependent)
source_points = np.array([[320, 520], [980, 520], [100, 750], [1100, 750]], dtype=np.float32)
destination_points = np.array([[320, 520], [980, 520], [320, 900], [980, 900]], dtype=np.float32)
H_matrix, _ = cv2.findHomography(source_points, destination_points)

def calibrate_mpp(frame_height):
    reference_lane_width_px = frame_height / 10  # approximate lane width in pixels
    lane_width_meters = 3.7  # average lane width in meters
    return lane_width_meters / reference_lane_width_px

# ---------------------------
# Video Capture and Writer Setup
# ---------------------------

cap = cv2.VideoCapture(video_path)
fps = int(cap.get(cv2.CAP_PROP_FPS))
W = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
H = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
if fps == 0:
    fps = 30

writer = cv2.VideoWriter(output_path, cv2.VideoWriter_fourcc(*"mp4v"), fps, (W, H), True)

meters_per_pixel = calibrate_mpp(H)

# ---------------------------
# Tracking: Speed Estimation Function
# ---------------------------

def estimate_speed(prev, curr, fps, track_id):
    prev_transformed = cv2.perspectiveTransform(np.array([[prev]], dtype=np.float32), H_matrix)[0][0]
    curr_transformed = cv2.perspectiveTransform(np.array([[curr]], dtype=np.float32), H_matrix)[0][0]
    dist_px = np.linalg.norm(np.array(curr_transformed) - np.array(prev_transformed))
    if dist_px > 100:
        return speed_dict.get(track_id, [0])[-1]  # use previous value if jump is too large
    time_diff = 1 / fps
    if time_diff == 0:
        return 0
    speed_mps = (dist_px * meters_per_pixel) / time_diff  # in m/s
    speed_kmh = speed_mps * 3.6
    if track_id in speed_dict:
        speed_dict[track_id].append(speed_kmh)
        if len(speed_dict[track_id]) > 10:
            speed_dict[track_id].pop(0)
        avg_speed = np.mean(speed_dict[track_id])
        if abs(speed_kmh - avg_speed) > 50:
            return avg_speed
        return avg_speed
    else:
        speed_dict[track_id] = [speed_kmh]
        return speed_kmh

# ---------------------------
# Initialize Counters and Data Structures
# ---------------------------

frame_count = 0
total_frames = 0
detected_vehicles = 0
total_vehicles = 0

centroid_dict = {}
speed_dict = {}
prev_boxes = {}

# For detection pipeline accuracy bookkeeping
detr_confidences = []
rcnn_confidences = []
yolo_confidences = []
detr_every_n_frames = 2

# ---------------------------
# Main Processing Loop
# ---------------------------

while True:
    ret, frame = cap.read()
    if not ret:
        break

    # Work on a copy for annotations
    annotated_frame = frame.copy()

    # --- Tracking Pipeline: YOLO + Deep SORT ---
    results = yolo_model(frame)[0]
    detections = []
    frame_vehicles = 0
    for r in results.boxes.data:
        x1, y1, x2, y2, conf, cls = r.tolist()
        if conf >= 0.5 and int(cls) in [2, 3, 5, 7]:  # filter for vehicles
            detections.append(([x1, y1, x2, y2], conf, 'vehicle'))
            frame_vehicles += 1
    total_vehicles += frame_vehicles
    tracks = deep_sort.update_tracks(detections, frame=frame)
    for track in tracks:
        if not track.is_confirmed() or track.time_since_update > 1:
            continue
        x1, y1, x2, y2 = track.to_tlbr()
        track_id = track.track_id
        centroid = [(x1 + x2) // 2, (y1 + y2) // 2]
        detected_vehicles += 1
        prev_boxes[track_id] = [x1, y1, x2, y2]
        speed = estimate_speed(centroid_dict.get(track_id, centroid), centroid, fps, track_id)
        centroid_dict[track_id] = centroid
        # Draw tracking rectangle (green) and speed label
        cv2.rectangle(annotated_frame, (int(x1), int(y1)), (int(x2), int(y2)), (0, 255, 0), 2)
        cv2.putText(annotated_frame, f"ID {track_id} | {speed:.1f} km/h", (int(x1), int(y1) - 10),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 255, 0), 2)

    # --- Detection Pipeline: Multi-Model Detection and Heatmap ---
    detected_boxes = []
    scores = []

    # Use DETR every few frames; otherwise, use YOLO and Faster R-CNN
    if frame_count % detr_every_n_frames == 0:
        image_pil = Image.fromarray(cv2.cvtColor(frame, cv2.COLOR_BGR2RGB))
        detr_boxes, detr_scores = detect_with_detr(image_pil)
        detected_boxes.extend(detr_boxes)
        scores.extend(detr_scores)
        detr_confidences.extend(detr_scores)
    else:
        yolo_boxes, yolo_scores = detect_with_yolo(frame)
        rcnn_boxes, rcnn_scores = detect_with_faster_rcnn(frame)
        detected_boxes.extend(yolo_boxes + rcnn_boxes)
        scores.extend(yolo_scores + rcnn_scores)
        yolo_confidences.extend(yolo_scores)
        rcnn_confidences.extend(rcnn_scores)

    # Apply Non-Maximum Suppression
    detected_boxes, scores = apply_nms(detected_boxes, scores)

    # Draw detection boxes (using blue for distinction)
    for (xmin, ymin, xmax, ymax) in detected_boxes:
        cv2.rectangle(annotated_frame, (xmin, ymin), (xmax, ymax), (255, 0, 0), 2)

    # Overlay a heatmap using the detection boxes
    annotated_frame = generate_heatmap(annotated_frame, detected_boxes)

    writer.write(annotated_frame)
    frame_count += 1
    total_frames += 1
    print(f"Processed Frame {frame_count}")

cap.release()
writer.release()
cv2.destroyAllWindows()

# ---------------------------
# Post-Processing Metrics
# ---------------------------
avg_vehicles_per_frame = total_vehicles / total_frames if total_frames > 0 else 1
accuracy_tracking = (detected_vehicles / total_vehicles) * 100 if total_vehicles > 0 else 0

detr_acc = compute_accuracy(detr_confidences)
rcnn_acc = compute_accuracy(rcnn_confidences)
yolo_acc = compute_accuracy(yolo_confidences)
overall_acc = compute_accuracy(detr_confidences + rcnn_confidences + yolo_confidences)

print(f"Processed {total_frames} frames, Avg Vehicles/Frame: {avg_vehicles_per_frame:.2f}, Estimated Accuracy: {accuracy_tracking:.2f}%")
print(f"Final DETR Accuracy: {detr_acc:.2f}")
print(f"Final Faster R-CNN Accuracy: {rcnn_acc:.2f}")
print(f"Final YOLOv8 Accuracy: {yolo_acc:.2f}")
print(f"Overall Accuracy: {overall_acc:.2f}")
print(f" Output saved to: {output_path}")

from google.colab import files
files.download('processed_video.mp4')

